In [1]:
import numpy as np

# Question 1
arr = np.arange(1, 21)
print("Array:", arr)
print("Shape:", arr.shape)
print("Max:", arr.max(), "Min:", arr.min())
print("Mean:", arr.mean(), "Std Dev:", arr.std())
matrix = arr.reshape(4, 5)
print("Matrix:\n", matrix)
print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape: (20,)
Max: 20 Min: 1
Mean: 10.5 Std Dev: 5.766281297335398
Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Second row: [ 6  7  8  9 10]
Third column: [ 3  8 13 18]


In [2]:
# Question 2
A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 10, 15, 20, 25])
print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)
print("Sum of A:", A.sum())

Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]
Sum of A: 150


In [3]:
import pandas as pd

# Question 3
data = {
    'Roll No': [101, 102, 103, 104, 105],
    'Name': ['Ravi', 'Priya', 'Kiran', 'Anu', 'Sita'],
    'Marks': [85, 92, 78, 88, 95]
}
df = pd.DataFrame(data)
print(df)
print("First 3 records:\n", df.head(3))
print("Average Marks:", df['Marks'].mean())
print("Highest Marks student:", df.loc[df['Marks'].idxmax(), 'Name'])
print("Lowest Marks student:", df.loc[df['Marks'].idxmin(), 'Name'])

def get_grade(marks):
    if marks >= 90: return 'A'
    elif marks >= 80: return 'B'
    else: return 'C'

df['Grade'] = df['Marks'].apply(get_grade)
print(df)


   Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95
First 3 records:
    Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
Average Marks: 87.6
Highest Marks student: Sita
Lowest Marks student: Kiran
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


In [4]:
# Question 4
products = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [50000, 500, 1200, 10000],
    'Quantity': [10, 50, 30, 15]
}
df_prod = pd.DataFrame(products)
df_prod['Total Value'] = df_prod['Price'] * df_prod['Quantity']
print(df_prod)
highest = df_prod.loc[df_prod['Total Value'].idxmax(), 'Product']
print("Highest total value product:", highest)
print("Overall inventory value:", df_prod['Total Value'].sum())

    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000
Highest total value product: Laptop
Overall inventory value: 711000


In [5]:
from sklearn.datasets import load_iris
import pandas as pd

# Question 5
iris = load_iris()
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_iris['target'] = iris.target

print("First 5 records:\n", df_iris.head())
print("Shape:", df_iris.shape)
print("Columns:", df_iris.columns.tolist())
print("Missing values:\n", df_iris.isnull().sum())
print("Summary statistics:\n", df_iris.describe())
print("Samples per class:\n", df_iris['target'].value_counts())

First 5 records:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
Shape: (150, 5)
Columns: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'target']
Missing values:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64
Summary statistics:
        sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843